dbt_code:
  outputs:
    dev:
      account: EKZDBYZ-TS53073
      database: AIRBNB
      password: Shandeep@200311
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 1
      type: snowflake
      user: SHANDEEP
      warehouse: COMPUTE_WH
  target: dev

